steps:
  # STEP 1: build image
  - name: gcr.io/cloud-builders/docker
    args:
      ["build", "-t", "gcr.io/$PROJECT_ID/${_SERVICE_NAME}:${SHORT_SHA}:latest", "."]
  # STEP 2: push image
  - name: "gcr.io/cloud-builders/docker"
    args:
      ["push", "gcr.io/$PROJECT_ID/${_SERVICE_NAME}:latest"]
  # STEP 3: deploy
  - name: "gcr.io/cloud-builders/gcloud"
    args:
      [
        "run",
        "deploy",
        "${_SERVICE_NAME}",
        "--image",
        "gcr.io/$PROJECT_ID/${_SERVICE_NAME}:${SHORT_SHA}:latest",
        "--region",
        "northamerica-northeast2-a",
        "--platform",
        "managed",
        "--allow-unauthenticated",
      ]
