steps:
  # STEP 0: build image
  - name: "docker"
    args:
      ["build", "-t", "${_REGION}-docker.pkg.dev/$PROJECT_ID/${_SERVICE_NAME}/test_image:${SHORT_SHA}", "."]
  # STEP 1: push container to artifact registry
  # - name: "docker"
  #   args:
  #     ["push", "${_REGION}-docker.pkg.dev/$PROJECT_ID/${_SERVICE_NAME}/test_image:{SHORT_SHA}"]
  # STEP 2: deploy to cloud run
  # - name: "gcloud"
  #   args:
  #     [
  #       "run",
  #       "deploy",
  #       "${_SERVICE_NAME}",
  #       "--image",
  #       "${_REGION}-docker.pkg.dev/$PROJECT_ID/${_SERVICE_NAME}/test_image",
  #       "--region",
  #       "${_REGION}",
  #       "--platform",
  #       "managed",
  #       "--allow-unauthenticated",
  #       "--port",
  #       "${_PORT}",
  #     ]
images:
  - "${_REGION}-docker.pkg.dev/$PROJECT_ID/${_SERVICE_NAME}/test_image:${SHORT_SHA}"
