steps:
  # STEP 1: build image
  - name: gcr.io/cloud-builders/docker
    args:
      ["build", "-t", "${_REGION}/$PROJECT_ID/${_SERVICE_NAME}:${SHORT_SHA}", "."]
  # STEP 2: push image to artifact registry
  - name: "gcr.io/cloud-builders/docker"
    args:
      ["push", "${_REGION}/$PROJECT_ID/${_SERVICE_NAME}"]
  # STEP 3: deploy
  - name: "gcr.io/cloud-builders/gcloud"
    args:
      [
        "run",
        "deploy",
        "${_SERVICE_NAME}",
        "--image",
        "${_REGION}/$PROJECT_ID/${_SERVICE_NAME}:latest",
        "--region",
        "${_REGION}",
        "--platform",
        "managed",
        "--allow-unauthenticated",
      ]
